image: maven:3.9.9-amazoncorretto-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - validate
  - build
  - test

checkstyle-job:
  stage: validate
  script:
    - mvn checkstyle:check
  artifacts:
    reports:
      junit: target/checkstyle-result.xml

build-job:
  stage: build
  script:
    - mvn compile

unit-test-job:
  stage: test
  script:
    - mvn test

integration-test-job:
  stage: test
  script:
    - mvn verify -Pskip-unit-tests

