image: maven:3.9.9-amazoncorretto-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_BUILD_ENABLED: "false"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - validate
  - build
  - test
  - docker_build

checkstyle-job:
  stage: validate
  script:
    - mvn checkstyle:check
  artifacts:
    reports:
      junit: target/checkstyle-result.xml

build-job:
  stage: build
  script:
    - mvn compile

unit-test-job:
  stage: test
  script:
    - mvn test

integration-test-job:
  stage: test
  script:
    - mvn verify -Pskip-unit-tests

docker_build:
  image: docker:27.3.1
  services:
    - docker:dind
  stage: docker_build
  rules:
    - if: '$DOCKER_BUILD_ENABLED == "true"'
  script:
    - mvn clean package
    - docker-compose build
    - docker-compose up -d
    - docker-compose down
  dependencies:
    - build-job


